FROM ghcr.io/uomresearchit/pb-base:latest

WORKDIR /app

# Install required R packages for app
COPY renv.lock .
COPY renv/activate.R ./renv/
COPY renv/settings.json ./renv/
RUN Rscript -e 'renv::restore()'

# Copy app
COPY R/ ./R/
COPY www/ ./www/
COPY app.R .

# Run the shiny app
CMD ["Rscript", "-e", "shiny::runApp(host='0.0.0.0',port=5678)"]
