FROM ghcr.io/uomresearchit/pb-base:latest

WORKDIR /rclient

# Install required R packages for rclient
COPY renv.lock .
COPY renv/activate.R ./renv/
COPY renv/settings.json ./renv/
RUN Rscript -e 'renv::restore()'

# Install minio client
RUN  <<installMC
    wget https://dl.min.io/client/mc/release/linux-amd64/mc
    chmod +x mc
    mv mc /usr/local/bin/
installMC

# Setup mmosquitto
RUN apt-get install -y mosquitto-clients

# Copy R code
COPY R/ ./R/

# Setup minio client and start MQTT client
ENTRYPOINT /bin/bash -c "\
  sed -e 's#localhost#minio#g' /rclient/config/minio/.secret_credentials.json > \
  /rclient/config/minio/.secret_credentials_docker.json && \
  mc alias import protein /rclient/config/minio/.secret_credentials_docker.json && \
  echo 'finished ENTRYPOINT' && \
  echo 'Starting MQTT client' && \
  Rscript -e \"source('R/mqtt_client.R'); run_mqtt_client()\""
