services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    # restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
    volumes:
      - minio_s3data:/s3data
      - ${HOME}/proteomics-web-app/app/data:/data
    command: server /s3data --console-address ":9001"

  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.12
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - '1883:1883'
      - '15672:15672'
    environment:
      - RABBITMQ_PLUGINS=rabbitmq_mqtt, rabbitmq_management
      - RABBITMQ_LOGS=-
      - RABBITMQ_CONF_FILE=/rabbitmq/rabbitmq.conf
    volumes:
      - rabbitmq_data:/bitnami/rabbitmq/mnesia
      - ${PWD}/config/rabbitmq/rabbitmq.conf:/rabbitmq/rabbitmq.conf
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rclient:
    build:
      context: .
      dockerfile: Dockerfile.rclient
    container_name: rclient
    restart: unless-stopped
    volumes:
      - ${HOME}/proteomics-web-app/app/data:/app/data
    depends_on:
      - minio
      - rabbitmq

volumes:
  rabbitmq_data:
    driver: local
  minio_s3data:
    driver: local
