name: build-push-rclient

on:
  workflow_dispatch:
    inputs:
      push_vb:
        description: "Push versioned '-branch_name' tag? ('-main' and '-dev' omitted)"
        required: false
        type: boolean
        default: true
      custom_tag:
        description: "Push custom tag? (leave blank to skip)"
        required: false
        type: string
        default: ""

# --------------------------------------------------------------------------------- #

jobs:
  rclient:
    uses: ./.github/workflows/build-test-push.yml
    with:
      container_name: pb-rclient
      org_name: ghcr.io/uomresearchit
      build_context: "./db"
      dockerfile: "./db/Dockerfile.rclient"
      test_script: |
        exit 0
      push_vb: ${{ github.event.inputs.push_vb == 'true' }}
      custom_tag: ${{ github.event.inputs.custom_tag }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: write
  